import sys 
import numpy as np

from ase.io import read, write
from ase import Atoms 

# Hierarhical clustering using scipy
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import squareform

# Package for K-medioid clustering 
import kmedoids # https://github.com/kno10/python-kmedoids

def comma_string_to_dict(s):   #  We now read info as a single-entry dictionary and split 
                               #  the string (value) into fields
    items = [item.strip() for item in s.split(',')]
    return dict(zip(items[0::2], items[1::2]))

def kabsch_align(P, Q):
    """
    Align P to Q using the Kabsch algorithm.
    P and Q are (N,3) arrays of positions.
    Returns the rotated P, the rotation matrix U, and the translation vector.
    """
    # Center both sets of coordinates
    Pc = P - P.mean(axis=0)
    Qc = Q - Q.mean(axis=0)

    # Compute covariance matrix
    C = Pc.T @ Qc

    # Singular value decomposition
    V, S, Wt = np.linalg.svd(C)
    d = np.sign(np.linalg.det(V @ Wt))
    U = V @ np.diag([1, 1, d]) @ Wt

    # Rotate P to match Q
    P_rot = Pc @ U

    # Translation to match Q's centroid
    translation = Q.mean(axis=0) - P_rot.mean(axis=0)

    # Aligned
    P_aligned = P_rot + translation 

    # RMSD
    rmsd = np.sqrt(((P_aligned - Q) ** 2).mean())

    return rmsd , U , translation

# =================================
# MAIN
# =================================

if len(sys.argv) != 2:
        print("Usage: python filter_conformer.py  <filename.xyz>")
        sys.exit(1)

# Database file : Note the input xyz must have been generated by previous scripts
filename=sys.argv[1]
output=filename.replace('.xyz','_conf_filtered.xyz')
traj = read(filename, ":", format="extxyz", properties_parser=lambda s: {"title": s} )  # The properties line is parsed as a dictionary having a single-entry 

# Get array of idsml IDs associated to smiles codes
idsml=np.array([],dtype=np.uint32)
smiles=[]
for i, atoms in enumerate(traj):
    info=comma_string_to_dict( atoms.info["title"] )
    idsml=np.append( idsml, int(info["idsml"])) 
    smiles.append(info["smiles"])
    
# Get unique IDs 
idsml_unique=np.unique(idsml)
nunique=len(idsml_unique)
print(f'File {filename:s} contains {len(traj)} structures and {nunique} smiles codes')

# RMSD clustering 
first=True
rmsd_tol=1.0   # RMSD clustering threshold (1.0 Ang is quite reasonable)
iconf=0

for xid in idsml_unique:
    x=np.where( idsml == xid )[0]
    smx=smiles[ x[0] ] 
    nx=len(x)
    RMSD=np.zeros([nx,nx])
    
    for i in range(nx):
        RMSD[i,i]=0.0 
        atoms1=traj[ x[i] ]
        indx_noH = [k for k, s in enumerate(atoms1.get_chemical_symbols()) if s != 'H']  # RMSD involving only heavy atoms
        Q=atoms1.get_positions()[indx_noH,:]
        for j in range(i+1,nx):
            atoms2=traj[ x[j] ]
            P=atoms2.get_positions()[indx_noH,:]
            rmsd, U, translation=kabsch_align(P, Q)
            RMSD[i,j]=rmsd
            RMSD[j,i]=RMSD[i,j]
            if ( i == 0 ) :
                P_rot =  np.matmul( atoms2.get_positions() , U ) + translation
                traj[ x[j] ].set_positions( P_rot )

    if ( nx > 1 ) :
        rmsdmax=np.max(RMSD)
        # Hierarchical clustering: determines the number of optimal clusters
        Z = linkage(squareform(RMSD), method="average")
        labels = fcluster(Z, t=rmsd_tol, criterion="distance")
        nk=int(labels.max())
        # K-means clustering to get the representatives (medioids)
        result = kmedoids.fasterpam(RMSD, medoids=min(nk,nx), random_state=42)
        clus=result.medoids.tolist()
#       idclus=result.labels.tolist()
#       print('struct',nx,nk,smx,rmsdmax)
#       print('clus rep',clus)
#       print(RMSD)
        k=0
        for i in clus:
            atoms=traj[ x[i] ]
            info=atoms.info["title"]
            info=info+f',iconf,{k},'
            k=k+1
            if ( first ):
                write(output,atoms,comment=info,format='extxyz')
                first=False
            else:
                write(output,atoms,append=True,comment=info,format='extxyz')
            iconf=iconf+1
    else:
        info=atoms1.info["title"]
        info=info+',iconf,0,'
        if ( first ):
            write(output,atoms1,comment=info,format='extxyz')
            first=False
        else:
            write(output,atoms1,append=True,comment=info,format='extxyz')
        iconf=iconf+1


print(f' Only {iconf} structures/conformers out of {len(traj)} structures ')
print(f' are preserved after hierarchical clustering wih tol={rmsd_tol} Ang')
print(f' The output structures are saved in {output} with format=extxyz')

            
    




