import sys 
import numpy as np
import hashlib
import re

from ase.io import read, write
from ase import Atoms 

def smiles_hash(smiles):

    return int( hashlib.sha256(smiles.encode()).hexdigest(), 16) % (10**12)

def comma_string_to_dict(s):   #  We now read info as a single-entry dictionary and split 
                               #  the string (value) into fields
    items = [item.strip() for item in s.split(',')]
    return dict(zip(items[0::2], items[1::2]))

def kabsch_align(P, Q):
    """
    Align P to Q using the Kabsch algorithm.
    P and Q are (N,3) arrays of positions.
    Returns the rotated P, the rotation matrix U, and the translation vector.
    """
    # Center both sets of coordinates
    Pc = P - P.mean(axis=0)
    Qc = Q - Q.mean(axis=0)

    # Compute covariance matrix
    C = Pc.T @ Qc

    # Singular value decomposition
    V, S, Wt = np.linalg.svd(C)
    d = np.sign(np.linalg.det(V @ Wt))
    U = V @ np.diag([1, 1, d]) @ Wt

    # Rotate P to match Q
    P_rot = Pc @ U

    # Translation to match Q's centroid
    translation = Q.mean(axis=0) - P_rot.mean(axis=0)

    # Aligned
    P_aligned = P_rot + translation 

    # RMSD
    rmsd = np.sqrt(((P_aligned - Q) ** 2).mean())

    return rmsd , P_aligned

# =================================
# MAIN
# =================================

if len(sys.argv) != 2:
        print("Usage: python filter_enantiomers.py  <filename.xyz>")
        sys.exit(1)

# Database file : Note the input xyz must have been generated by previous scripts
# Atom ordering as generated by the posprocessing script is crucial!
filename=sys.argv[1]
output=filename.replace('.xyz','_stereo_filtered.xyz')
traj = read(filename, ":", format="extxyz", properties_parser=lambda s: {"title": s} )  # The properties line is parsed as a dictionary having a single-entry 

# Get array of idsml IDs associated to smiles codes
idsml=np.array([],dtype=np.uint32) # numerical hash of molecular formula
icen=np.array([],dtype=np.uint32) #  Each stereocenter is marked with either '@' or '@@'.
#  Because '@@' contains two '@' symbols, we use a regex to treat
# '@' and '@@' as single stereocenter indicators.
#  
# We read smiles codes, remove sterochemical information and generate new numerical hash
# 
for i, atoms in enumerate(traj):
    info=comma_string_to_dict( atoms.info["title"] )
    icen=np.append( icen , len ( re.findall(r'@{1,2}', info["smiles"] ) ) + 1 )
    flat_smiles= re.sub(r'@{1,2}', '', info["smiles"] )   # Removing stereochemical info
    idsml=np.append( idsml , smiles_hash ( flat_smiles  ) ) 
    
# Get unique IDs 
idsml_unique=np.unique(idsml)
nunique=len(idsml_unique)

print(f'File {filename:s} contains {len(traj)} structures and {nunique} flat smiles')

# RMSD analysis
first=True
rmsd_tol=0.5          # lower RMSD threshold for considering potential i-j enantiomeric pairs
rmsd_tol_mirror=0.10  # upper RMSD threshold for assuming i and j(mirror) are identical
istereo=0

for xid in idsml_unique:
    x=np.where( idsml == xid )[0]
    nx=len(x)
    RMSD=np.zeros([nx,nx])
    ifilter=np.ones(nx,dtype=np.int32)
    
    for i in range(nx):
        RMSD[i,i]=0.0 
        atoms1=traj[ x[i] ]
        indx_noH = [k for k, s in enumerate(atoms1.get_chemical_symbols()) if s != 'H']  # RMSD involving only heavy atoms
        Q=atoms1.get_positions()[indx_noH,:]
        for j in range(i+1,nx):
            atoms2=traj[ x[j] ]
            P=atoms2.get_positions()[indx_noH,:]
            rmsd, P_aligned=kabsch_align(P, Q)
            RMSD[i,j]=rmsd
            # Mirror image 
            P = P_aligned * np.array([-1, 1, 1])
            rmsd, P_aligned=kabsch_align(P, Q)
            RMSD[j,i]=rmsd
#   print(RMSD)
#   print(icen[x]) 

    # Analyzing RMSD pair elements
    if ( nx > 1 ) :
        for i in range(nx):
            for j in range(i+1,nx):
                rmsd=RMSD[i,j]
                rmsd_mirror=RMSD[j,i]
                if ( rmsd >= rmsd_tol ) & ( rmsd_mirror <= rmsd_tol_mirror ) :
                    ifilter[j]=0  # If j mirror superposes onto i then j is a true (same conformation) enantiomer of i 
                    istereo+=1


    for i in range(nx):
        if ( ifilter[i] ): 
            atoms=traj[ x[i] ]
            info=atoms.info["title"]
            if ( first ):
                write(output,atoms,comment=info,format='extxyz')
                first=False
            else:
                write(output,atoms,append=True,comment=info,format='extxyz')


print(f' {istereo} i-j enantiomeric pairs found in the {len(traj)} structures ')
print(f' wih tol>{rmsd_tol} Ang  between i-j and tol<{rmsd_tol_mirror} between i-j(mirror)')
print(f' Only enantiomer i is preserved')
print(f' The output {len(traj)-istereo} structures are saved in {output} with format=extxyz')

