"""
tanimoto_similarity.py
----------------------
Compute all pairwise Tanimoto similarity indices between molecules using
OpenBabel fingerprints.  Supports three input modes:

  1. extxyz / xyz file  – 3-D structures read with ASE, bonding perceived
                          by OpenBabel from coordinates.
  2. SMILES file (.smi) – plain text, one SMILES per line, optional name
                          column (space/tab separated).
  3. Inline SMILES      – comma-separated SMILES passed directly on the
                          command line with --smiles.

Usage
-----
  # extxyz (original behaviour)
  python tanimoto_similarity.py structures.extxyz

  # SMILES file
  python tanimoto_similarity.py molecules.smi

  # Inline SMILES list
  python tanimoto_similarity.py --smiles "c1ccccc1,CCO,CC(=O)O,c1cccnc1"

  # Choose fingerprint and output path
  python tanimoto_similarity.py molecules.smi --fp ecfp4 --out tanimoto.png

Fingerprint choices (--fp):
  fp2              path-based, 1024 bits (default)
  fp3 / fp4        SMARTS-pattern fingerprints
  maccs            166-bit MACCS keys
  ecfp0 … ecfp10  extended-connectivity (Morgan) fingerprints
"""

import argparse
import math
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from itertools import combinations

import numpy as np
from openbabel import pybel


# ─────────────────────────────────────────────────────────────────────────────
# Molecule loading
# ─────────────────────────────────────────────────────────────────────────────

def load_from_smiles_list(smiles_list, names=None):
    """
    Convert a list of SMILES strings → (pybel molecules, labels).
    Invalid SMILES are skipped with a warning.
    """
    mols, labels = [], []
    for i, smi in enumerate(smiles_list):
        smi = smi.strip()
        if not smi:
            continue
        name = names[i] if names else smi
        try:
            mol = pybel.readstring("smi", smi)
            mol.addh()           # add implicit H for better fingerprints
            mols.append(mol)
            labels.append(name)
        except Exception as e:
            print(f"[WARN] Skipping SMILES '{smi}': {e}", file=sys.stderr)
    return mols, labels


def load_from_smi_file(path):
    """
    Read a .smi file (one SMILES per line, optional name in second column).
    Returns (pybel molecules, labels).
    """
    smiles_list, names = [], []
    with open(path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)      # split on any whitespace, max 2
            smi = parts[0]
            name = parts[1].strip() if len(parts) > 1 else f"mol_{lineno}"
            smiles_list.append(smi)
            names.append(name)
    return load_from_smiles_list(smiles_list, names)


def load_from_extxyz(path):
    """
    Read an extxyz/xyz file with ASE; convert to pybel molecules via XYZ
    strings (OpenBabel perceives bonds from 3-D coordinates).
    Returns (pybel molecules, labels).
    """
    from ase.io import read as ase_read

    print(f"[INFO] Reading 3-D structures from: {path}")
    frames = ase_read(path, index=":")
    if not frames:
        sys.exit("[ERROR] No structures found in the file.")
    print(f"[INFO] Loaded {len(frames)} structure(s).")

    mols, labels = [], []
    for i, atoms in enumerate(frames):
        lines = [str(len(atoms)), "generated by ASE"]
        for sym, pos in zip(atoms.get_chemical_symbols(),
                            atoms.get_positions()):
            lines.append(f"{sym}  {pos[0]:.6f}  {pos[1]:.6f}  {pos[2]:.6f}")
        xyz_str = "\n".join(lines)
        mol = pybel.readstring("xyz", xyz_str)
        mol.OBMol.ConnectTheDots()
        mol.OBMol.PerceiveBondOrders()
        mols.append(mol)
        labels.append(atoms.get_chemical_formula())

    # Make labels unique when formulas repeat
    from collections import Counter
    counts = Counter(labels)
    seen = {}
    unique_labels = []
    for lab in labels:
        if counts[lab] > 1:
            seen[lab] = seen.get(lab, 0) + 1
            unique_labels.append(f"{lab}_{seen[lab]}")
        else:
            unique_labels.append(lab)

    return mols, unique_labels


# ─────────────────────────────────────────────────────────────────────────────
# Fingerprints & Tanimoto
# ─────────────────────────────────────────────────────────────────────────────

FP_LENGTHS = {"fp2": 1024, "fp3": 55, "fp4": 307, "maccs": 166}


def get_fingerprint(mol, fp_type="fp2", nbits=2048):
    """Return a numpy bool array for the molecule's fingerprint."""
    fp = mol.calcfp(fp_type.lower())
    bits_set = set(fp.bits)
    length = FP_LENGTHS.get(fp_type.lower(), nbits)
    arr = np.zeros(length, dtype=bool)
    for b in bits_set:
        arr[(b - 1) % length] = True
    return arr


def tanimoto(fp_a, fp_b):
    """Tanimoto (Jaccard) coefficient for two boolean numpy arrays."""
    a_and_b = np.count_nonzero(fp_a & fp_b)
    a_or_b  = np.count_nonzero(fp_a | fp_b)
    return a_and_b / a_or_b if a_or_b > 0 else 0.0


# ── Worker function (module-level so it is picklable) ─────────────────────────

def _tanimoto_chunk(args):
    """
    Compute Tanimoto values for a chunk of (i, j) index pairs.

    Parameters
    ----------
    args : (fps_array, pairs)
        fps_array – (N, L) uint8 array of all fingerprints
        pairs     – list of (i, j) tuples for this chunk

    Returns
    -------
    list of (i, j, tanimoto_value)
    """
    fps_array, pairs = args
    results = []
    for i, j in pairs:
        fp_a = fps_array[i].view(bool)
        fp_b = fps_array[j].view(bool)
        a_and_b = int(np.count_nonzero(fp_a & fp_b))
        a_or_b  = int(np.count_nonzero(fp_a | fp_b))
        t = a_and_b / a_or_b if a_or_b > 0 else 0.0
        results.append((i, j, t))
    return results


def compute_tanimoto_matrix(mols, fp_type="fp2", nbits=2048, n_workers=None,
                            chunk_size=None):
    """
    Compute the (N×N) symmetric Tanimoto matrix in parallel.

    Fingerprints are computed sequentially in the main process (pybel objects
    are not picklable), then the arithmetic is distributed across worker
    processes using chunks of index pairs.

    Parameters
    ----------
    mols       : list of pybel molecules
    fp_type    : OpenBabel fingerprint name
    nbits      : bit-vector length for ECFP fingerprints
    n_workers  : number of worker processes (default: os.cpu_count())
    chunk_size : pairs per chunk (default: auto-tuned)

    Returns
    -------
    matrix : (N, N) numpy float64 symmetric Tanimoto matrix
    """
    import os

    n = len(mols)
    n_pairs = n * (n - 1) // 2
    n_workers = n_workers or os.cpu_count() or 1

    # ── Step 1: fingerprints (main process only – pybel is not picklable) ────
    print(f"[INFO] Computing {fp_type.upper()} fingerprints for {n} molecules …")
    t0 = time.perf_counter()
    fps_list = [get_fingerprint(m, fp_type, nbits) for m in mols]
    fp_len = fps_list[0].shape[0]
    # Pack into a contiguous uint8 array for cheap inter-process transfer
    fps_array = np.array(fps_list, dtype=np.uint8)
    print(f"       done in {time.perf_counter()-t0:.2f}s  "
          f"(fp length = {fp_len} bits)")

    # ── Step 2: parallel Tanimoto arithmetic ──────────────────────────────────
    # Auto-tune chunk size: aim for ~4× as many chunks as workers so the
    # scheduler stays busy, but never smaller than 10 000 pairs per chunk.
    if chunk_size is None:
        chunk_size = max(10_000, math.ceil(n_pairs / (n_workers * 4)))

    all_pairs = list(combinations(range(n), 2))
    chunks = [all_pairs[k:k + chunk_size]
              for k in range(0, len(all_pairs), chunk_size)]

    # Parallelism only pays off when IPC serialisation cost is small relative
    # to the arithmetic work.  Empirically that requires > ~1 M pairs and at
    # least 2 workers.  For smaller datasets the numpy-vectorised serial path
    # is faster.
    use_parallel = (n_pairs >= 1_000_000) and (n_workers > 1)

    print(f"[INFO] Calculating {n_pairs} pairwise Tanimoto values "
          f"({'parallel' if use_parallel else 'serial'}"
          + (f", {n_workers} workers, {len(chunks)} chunks" if use_parallel else "")
          + ") …")

    matrix = np.zeros((n, n), dtype=np.float64)
    np.fill_diagonal(matrix, 1.0)

    t1 = time.perf_counter()
    if use_parallel:
        work = [(fps_array, chunk) for chunk in chunks]
        completed = 0
        with ProcessPoolExecutor(max_workers=n_workers) as pool:
            futures = {pool.submit(_tanimoto_chunk, w): w for w in work}
            for fut in as_completed(futures):
                for i, j, val in fut.result():
                    matrix[i, j] = val
                    matrix[j, i] = val
                completed += len(futures[fut][1])
                pct = 100 * completed / n_pairs
                print(f"\r       {completed:>10,} / {n_pairs:,} pairs  "
                      f"({pct:5.1f}%)", end="", flush=True)
        print()   # newline after progress
    else:
        # Vectorised serial path using numpy:
        #   intersection(i,j) = dot(fp_i, fp_j)   (boolean dot product)
        #   union(i,j)        = |fp_i| + |fp_j| - intersection(i,j)
        fp_f = fps_array.astype(np.float32)       # (N, L)
        counts = fps_array.sum(axis=1).astype(np.float32)   # (N,) bit counts
        # intersection matrix: (N, N)
        inter = fp_f @ fp_f.T
        # union matrix: broadcast row+col counts minus intersection
        union = counts[:, None] + counts[None, :] - inter
        with np.errstate(divide="ignore", invalid="ignore"):
            tan = np.where(union > 0, inter / union, 0.0)
        np.fill_diagonal(tan, 1.0)
        matrix = tan.astype(np.float64)

    elapsed = time.perf_counter() - t1
    rate = n_pairs / elapsed if elapsed > 0 else float("inf")
    print(f"       done in {elapsed:.2f}s  ({rate:,.0f} pairs/s)")
    return matrix


# ─────────────────────────────────────────────────────────────────────────────
# Output
# ─────────────────────────────────────────────────────────────────────────────

def print_matrix(matrix, labels):
    col_w = max(max(len(l) for l in labels), 6)
    sep   = "  "
    header = " " * (col_w + len(sep)) + sep.join(f"{l:>{col_w}}" for l in labels)
    bar = "=" * len(header)
    print("\nTanimoto Similarity Matrix")
    print(bar)
    print(header)
    print("-" * len(header))
    for label, row in zip(labels, matrix):
        row_str = sep.join(f"{v:{col_w}.4f}" for v in row)
        print(f"{label:>{col_w}}{sep}{row_str}")
    print(bar)


def print_stats(matrix):
    n = matrix.shape[0]
    upper = matrix[np.triu_indices(n, k=1)]
    print(f"\nSummary statistics ({len(upper)} pairs)")
    print(f"  Min    : {upper.min():.4f}")
    print(f"  Max    : {upper.max():.4f}")
    print(f"  Mean   : {upper.mean():.4f}")
    print(f"  Median : {np.median(upper):.4f}")
    print(f"  Std    : {upper.std():.4f}")
    return upper


def save_histogram(matrix, labels, output_path, fp_type, input_mode):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm

    n = matrix.shape[0]
    upper = matrix[np.triu_indices(n, k=1)]

    # ── Build 2-D scatter data: T(i,j) vs T(i,k) for all i, j<k ─────────────
    if n >= 3:
        vals_x, vals_y = [], []
        for mol in range(n):
            partners = [p for p in range(n) if p != mol]
            for a, b in combinations(partners, 2):
                vals_x.append(matrix[mol, a])
                vals_y.append(matrix[mol, b])
        vals_x = np.array(vals_x)
        vals_y = np.array(vals_y)
    else:
        vals_x = vals_y = upper

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5),
                             gridspec_kw={"width_ratios": [2, 1]})
    mode_tag = {"smiles": "inline SMILES", "smi": ".smi file",
                "extxyz": "extxyz"}.get(input_mode, input_mode)
    fig.suptitle(
        f"Tanimoto Similarity  —  {fp_type.upper()} fingerprints  "
        f"({mode_tag})\n{n} molecules · {len(upper)} pairs",
        fontsize=13, fontweight="bold"
    )

    # ── Left panel: 2-D density map ──────────────────────────────────────────
    ax = axes[0]
    bins = np.linspace(0, 1, 51)
    h2d, xedges, yedges = np.histogram2d(vals_x, vals_y, bins=bins)
    h2d[h2d == 0] = np.nan
    norm = LogNorm(vmin=1, vmax=np.nanmax(h2d)) if np.nanmax(h2d) > 1 else None
    im = ax.pcolormesh(xedges, yedges, h2d.T,
                       cmap="plasma", norm=norm, shading="auto")
    fig.colorbar(im, ax=ax, label="Count (log scale)" if norm else "Count")
    ax.set_xlabel("Tanimoto(mol$_i$, mol$_j$)", fontsize=11)
    ax.set_ylabel("Tanimoto(mol$_i$, mol$_k$)  [j ≠ k]", fontsize=11)
    ax.set_title("2-D Tanimoto density map", fontsize=11)
    ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    ax.plot([0, 1], [0, 1], "w--", lw=0.8, alpha=0.5)

    # ── Right panel: 1-D distribution ────────────────────────────────────────
    ax2 = axes[1]
    bins1d = np.linspace(0, 1, 26)
    counts, edges = np.histogram(upper, bins=bins1d)
    ax2.bar(edges[:-1], counts, width=np.diff(edges),
            color="steelblue", edgecolor="white", linewidth=0.5, align="edge")
    ax2.axvline(upper.mean(),    color="tomato", lw=1.5, ls="--",
                label=f"mean = {upper.mean():.3f}")
    ax2.axvline(np.median(upper), color="gold",  lw=1.5, ls=":",
                label=f"median = {np.median(upper):.3f}")
    ax2.set_xlabel("Tanimoto similarity", fontsize=11)
    ax2.set_ylabel("Pair count", fontsize=11)
    ax2.set_title("Pairwise distribution", fontsize=11)
    ax2.set_xlim(0, 1)
    ax2.legend(fontsize=9)

    # ── Molecule labels as a small annotation ────────────────────────────────
    if n <= 20:
        label_txt = "\n".join(
            f"{i}: {lab}" for i, lab in enumerate(labels)
        )
        fig.text(0.01, 0.01, label_txt, fontsize=6.5, va="bottom",
                 family="monospace", color="0.4")

    plt.tight_layout(rect=[0, 0.04 if n <= 20 else 0, 1, 1])
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[INFO] Histogram saved → {output_path}")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Pairwise Tanimoto similarity from extxyz, .smi files, "
                    "or inline SMILES strings.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python tanimoto_similarity.py structures.extxyz
  python tanimoto_similarity.py molecules.smi --fp ecfp4
  python tanimoto_similarity.py --smiles "c1ccccc1,CCO,CC(=O)O,c1cccnc1"
  python tanimoto_similarity.py --smiles "aspirin,ibuprofen" --fp maccs
        """)

    # Mutually exclusive input modes
    inp = p.add_mutually_exclusive_group(required=True)
    inp.add_argument("input", nargs="?",
                     help="Path to an .extxyz/.xyz file OR a .smi SMILES file")
    inp.add_argument("--smiles", metavar="SMILES1,SMILES2,...",
                     help="Comma-separated SMILES strings (inline, no file needed)")

    p.add_argument("--fp", default="fp2",
                   help="Fingerprint type: fp2 (default), fp3, fp4, maccs, "
                        "ecfp0–ecfp10")
    p.add_argument("--bits", type=int, default=2048,
                   help="Bit-vector length for ECFP fingerprints (default: 2048)")
    p.add_argument("--workers", type=int, default=None,
                   help="Number of parallel worker processes "
                        "(default: all logical CPUs). Set to 1 to disable parallelism.")
    p.add_argument("--chunk-size", type=int, default=None,
                   help="Pairs per work chunk (default: auto-tuned)")
    p.add_argument("--out", default="tanimoto_histogram.png",
                   help="Output histogram image path (default: tanimoto_histogram.png)")
    p.add_argument("--no-plot", action="store_true",
                   help="Skip histogram generation")
    return p.parse_args()


def main():
    args = parse_args()

    # ── 1. Load molecules ───────────────────────────────────────────────────
    if args.smiles:
        # Inline SMILES list
        raw = [s.strip() for s in args.smiles.split(",") if s.strip()]
        print(f"[INFO] Parsing {len(raw)} inline SMILES …")
        mols, labels = load_from_smiles_list(raw)
        input_mode = "smiles"

    else:
        path = args.input
        if not os.path.isfile(path):
            sys.exit(f"[ERROR] File not found: {path}")

        ext = os.path.splitext(path)[1].lower()
        if ext in (".smi", ".smiles"):
            print(f"[INFO] Reading SMILES file: {path}")
            mols, labels = load_from_smi_file(path)
            input_mode = "smi"
        else:
            # Default: treat as extxyz / xyz
            mols, labels = load_from_extxyz(path)
            input_mode = "extxyz"

    if len(mols) < 2:
        sys.exit(f"[ERROR] Need at least 2 valid molecules, got {len(mols)}.")

    print(f"[INFO] {len(mols)} molecule(s) loaded successfully.")
    for i, (mol, lab) in enumerate(zip(mols, labels)):
        formula = mol.formula
        print(f"       [{i:>3d}] {lab:<30s}  {formula}")

    # ── 2. Tanimoto matrix ──────────────────────────────────────────────────
    matrix = compute_tanimoto_matrix(mols, args.fp, args.bits,
                                     n_workers=args.workers,
                                     chunk_size=args.chunk_size)

    # ── 3. Print & stats ────────────────────────────────────────────────────
#   print_matrix(matrix, labels)
    print_stats(matrix)

    # ── 4. Histogram ────────────────────────────────────────────────────────
    if not args.no_plot:
        save_histogram(matrix, labels, args.out, args.fp, input_mode)


if __name__ == "__main__":
    main()
